"""Self-contained inference CLI: load an SSMForge GGUF and generate text.

Usage:
    ssmforge run --model ./out-xxx/model.gguf --prompt "Hello"
    ssmforge run --model ./out-xxx/model.gguf --interactive

No ollama, no llama.cpp runtime, no external service. Just PyTorch.

NOTE: The loaded model's SSM layers use the pure-PyTorch fallback
(_FallbackMambaLayer) when mamba-ssm is not installed (Python 3.13+).
On Python <3.13 with [mamba] extra installed, the real CUDA Mamba2
kernels run. Either way, output quality is gibberish for v0.2 because
distillation is still a 2-step stub — we are validating the pipeline,
not training meaningful outputs.
"""

from __future__ import annotations

import argparse
import sys
import warnings
from pathlib import Path

import torch

from ssmforge.runtime.loader import load_hybrid_model_from_gguf


def _encode(text: str, vocab_size: int) -> torch.Tensor:
    """Encode text to token ids, clamped to the model's actual vocab size.

    We try to load a real tokenizer; if the encode produces ids beyond
    the model's vocab (which happens with a vocab-mismatched tokenizer),
    we fall back to byte encoding that's guaranteed to fit.
    """
    try:
        from transformers import AutoTokenizer
        for guess in ["TinyLlama/TinyLlama-1.1B-Chat-v1.0", "Qwen/Qwen2-0.5B-Instruct"]:
            try:
                tokenizer = AutoTokenizer.from_pretrained(guess, trust_remote_code=True)
                ids = tokenizer.encode(text, return_tensors="pt")
                # If the tokenizer produced ids outside the model's vocab,
                # reject and try a fallback
                if int(ids.max()) >= vocab_size or int(ids.min()) < 0:
                    raise ValueError("tokenizer ids exceed model vocab")
                return ids
            except Exception:
                continue
    except Exception:
        pass
    # Fallback: byte encoding (always within range for vocab >= 256)
    ids = [min(b, vocab_size - 1) for b in text.encode("utf-8")[:64]]
    return torch.tensor([ids], dtype=torch.long)


def _decode(ids: torch.Tensor) -> str:
    """Decode token ids back to text. Without tokenizer this is approximate."""
    out = ids.tolist()
    if isinstance(out[0], list):
        out = out[0]
    try:
        from transformers import AutoTokenizer
        # Best-effort tokenizer lookup for friendly output
        for guess in ["TinyLlama/TinyLlama-1.1B-Chat-v1.0", "Qwen/Qwen2-0.5B-Instruct"]:
            try:
                tokenizer = AutoTokenizer.from_pretrained(guess, trust_remote_code=True)
                return tokenizer.decode(out, skip_special_tokens=True)
            except Exception:
                continue
    except Exception:
        pass
    return "".join(chr(i) if 32 <= i < 127 else "?" for i in out).strip()


def _greedy_generate(model, input_ids, max_new_tokens, eos_token_id=None):
    """Greedy autoregressive generation."""
    device = next(model.parameters()).device
    out = input_ids.to(device)
    for _ in range(max_new_tokens):
        with torch.no_grad():
            logits = model(input_ids=out).logits
        next_id = logits[:, -1].argmax(dim=-1, keepdim=True)
        out = torch.cat([out, next_id], dim=-1)
        if eos_token_id is not None and int(next_id.item()) == eos_token_id:
            break
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="ssmforge run",
        description=(
            "Run inference on an SSMForge GGUF (self-contained, no ollama).\n\n"
            "NOTE: SSMForge GGUFs do NOT load in mainstream runtimes (llama.cpp,\n"
            "ollama, LM Studio, etc.) — those reject them with errors like\n"
            "`unknown model architecture: 'ssmforge'`. This command is the only\n"
            "way to run inference on them today (in pure PyTorch).\n\n"
            "Also: SSMForge is experimental. Output quality is unverified.\n"
            "Do not use in production environments."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--model", required=True, help="Path to SSMForge F16/Q4_K GGUF")
    parser.add_argument("--prompt", default=None, help="Text prompt. Required unless --interactive.")
    parser.add_argument("--interactive", action="store_true", help="REPL mode")
    parser.add_argument("--max-new-tokens", type=int, default=30)
    parser.add_argument("--device", default="cpu", choices=["cpu", "cuda"])
    parser.add_argument("--no-quiet", action="store_true", help="Print model metadata")
    parser.add_argument(
        "--output", "-o", default=None,
        help="Write generated text to this file (UTF-8). Useful on Windows consoles "
             "that can't print all generated bytes."
    )
    args = parser.parse_args(argv)

    gguf_path = Path(args.model)
    if not gguf_path.exists():
        print(f"Error: model file not found: {gguf_path}", file=sys.stderr)
        return 1

    print(f"Loading {gguf_path}...", file=sys.stderr)
    print(
        "WARNING: experimental software — output quality not verified. Not for production.",
        file=sys.stderr,
    )
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        try:
            model, metadata = load_hybrid_model_from_gguf(gguf_path, device=args.device)
        except Exception as e:
            print(f"Failed to load model: {e}", file=sys.stderr)
            return 1

    if args.no_quiet or args.interactive:
        n_embd = metadata.get("ssmforge.embedding_length")
        n_layers = metadata.get("ssmforge.block_count")
        n_ctx = metadata.get("ssmforge.context_length")
        arch = metadata.get("general.architecture")
        print(f"  arch: {arch}", file=sys.stderr)
        print(f"  hidden_size: {n_embd}", file=sys.stderr)
        print(f"  block_count: {n_layers}", file=sys.stderr)
        print(f"  context_length: {n_ctx}", file=sys.stderr)
        ssm_count = len(model.config.ssm_layer_indices)
        print(f"  ssm_layers: {ssm_count} of {n_layers}", file=sys.stderr)
        print(f"  device: {args.device}", file=sys.stderr)

    model.eval()

    vocab_size = int(model.config.vocab_size)

    if args.interactive:
        print("\nSSMForge interactive mode. Ctrl-D or empty line to exit.\n", file=sys.stderr)
        # Reconfigure stdout for UTF-8 if possible (Windows console fix)
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass
        try:
            while True:
                prompt = input(">>> ")
                if not prompt:
                    break
                input_ids = _encode(prompt, vocab_size)
                out = _greedy_generate(model, input_ids, max_new_tokens=args.max_new_tokens)
                try:
                    print(_decode(out[0]))
                except UnicodeEncodeError:
                    safe = _decode(out[0]).encode("ascii", errors="replace").decode("ascii")
                    print(safe)
                print()
        except (EOFError, KeyboardInterrupt):
            print("\nBye.", file=sys.stderr)
        return 0

    if args.prompt is None:
        parser.error("Either --prompt or --interactive is required")

    input_ids = _encode(args.prompt, vocab_size)
    out = _greedy_generate(model, input_ids, max_new_tokens=args.max_new_tokens)

    decoded = _decode(out[0])

    # If --output is given, always write to file (UTF-8, safe on all OSes).
    # Otherwise, try to print but fall back to file if stdout encoding fails.
    if args.output:
        out_path = Path(args.output)
        out_path.write_text(decoded, encoding="utf-8")
        print(f"\nGenerated (saved to {out_path}):", file=sys.stderr)
        try:
            print(decoded)
        except UnicodeEncodeError:
            # Last-resort: print ASCII-safe version
            safe = decoded.encode("ascii", errors="replace").decode("ascii")
            print(safe)
        return 0

    print("\nGenerated:")
    try:
        print(decoded)
    except UnicodeEncodeError:
        # Windows console often uses cp1252 which can't encode many Unicode
        # codepoints that real model output uses. Reconfigure stdout to UTF-8
        # if possible; otherwise fall back to ASCII-safe.
        try:
            sys.stdout.reconfigure(encoding="utf-8")
            print(decoded)
        except Exception:
            safe = decoded.encode("ascii", errors="replace").decode("ascii")
            print(safe)
            print(
                "\n[Note: stdout encoding couldn't print all characters. "
                "Re-run with --output FILE to capture full UTF-8 output.]",
                file=sys.stderr,
            )
    return 0


if __name__ == "__main__":
    sys.exit(main())
